### ISSUE TITLE
support deep URLs

### ISSUE THREAD

**Issue by zeke** [nice-registry/ghub.io#11]
See https://github.com/juliangruber/ghub.io/blob/f5dffef663588cb0e58e9897553a1f786f808762/test/deep-urls.js

**Comment by zeke** [comment]
I just close all the open issues except this one. If anyone wants this feature, please implement it and I'll ship it. :)

**Comment by tunnckoCore** [comment]
@zeke don't see why we need wikis or such, but we need support for monorepos. This most probably should be fixed in `all-the-package-repos`.

**Comment by zeke** [comment]
Hey @tunnckoCore no one has expressed a need for this in the last two years, so I'm not inclined to work on it now. If you need this and want to work on it, I'd be happy to help get it across the finish line.
