### ISSUE TITLE
Point DNS at Heroku

### ISSUE THREAD

**Issue by zeke** [nice-registry/ghub.io#14]
@juliangruber I've added the domains on the Heroku app. I think all that's needed now is DNS:

`ghub.io.herokudns.com`
`www.ghub.io.herokudns.com`

![image](https://user-images.githubusercontent.com/2289/33160571-55e3eb72-cfd2-11e7-9895-365f7fd2c729.png)

**Comment by juliangruber** [comment]
waiting for the dns changes to propagate

**Comment by juliangruber** [comment]
that was fast :| http://ghub.io/express

**Comment by juliangruber** [comment]
i used iwantmyname's feature to set up heroku for the domain but something seems wrong. http://www.ghub.io/express works however

**Comment by juliangruber** [comment]
<img width="981" alt="screen shot 2017-11-23 at 13 41 31" src="https://user-images.githubusercontent.com/10247/33173335-091a84e0-d054-11e7-937e-4a62ddc0bda1.png">

those are the records it created

**Comment by juliangruber** [comment]
it works now

**Comment by zeke** [comment]
🎉
