### ISSUE TITLE
Open current repo

### ISSUE THREAD

**Issue by Apidcloud** [nice-registry/ghub.io#37]
Good evening!

Just came across this repo, and I find it extremely cool 💯 

How about adding the option to open the current project (if any)? One can obviously type `ghub <name_of_repo>`, but something like `ghub current` would be cool I guess 😄 

Just an idea. Let me know if I can help with that in some way (some guidance would be nice).

Thanks!

**Comment by zeke** [comment]
For context, the current behavior of `ghub` without an arguments is to display USAGE:

```
$ ghub 
To use ghub, specify one or many package names.
Examples:

ghub express
ghub choo chai chalk
```

I'd be open to the idea of the default behavior changing to "open the repository in package.json of process.cwd()" and falling back to usage if that condition isn't met. 🤔

**Comment by Apidcloud** [comment]
That seems a good way to do it! 

I'll take a look at it when I have the chance (and if no1 else does it before).

Thanks!

**Comment by zeke** [comment]
I forgot to mention, `npm repo` is an existing command that does what you're looking for, @Apidcloud. 

I'm going to close this issue, but feel free to chime in if you still care about changing the default behavior of the `ghub` CLI. Thanks!
