### ISSUE TITLE
migration plan

### ISSUE THREAD

**Issue by zeke** [nice-registry/ghub.io#8]
This is a followup to https://github.com/juliangruber/ghub.io/issues/17

- [x] invite @juliangruber and @rvagg to @nice-registry org (visit https://github.com/nice-registry to accept the invitation.)
- [x] rename nice-registry/package.land repo to nice-registry/ghub.io
- [x] update the readme: https://github.com/nice-registry/ghub.io/pull/9
- [x] retire the old juliangruber/ghub.io with a notice in the README: https://github.com/juliangruber/ghub.io/pull/28
- [x] ~~re~~implement the CLI functionality function of the ghub module: https://github.com/nice-registry/ghub.io/pull/12
- [x] point ghub.io DNS to Heroku: https://github.com/nice-registry/ghub.io/issues/14
- [x] `npm owner add zeke ghub` (@juliangruber)
- [x] set up semantic-release to autopublish ghub changes to npm

**Comment by juliangruber** [comment]
I made you an owner on npm

**Comment by juliangruber** [comment]
Once we agree this works sufficiently well, @rvagg can shut down the original service

**Comment by zeke** [comment]
Everything on this list is done!

@juliangruber I want to make some noise about the updates, but would love to get HTTPS nailed down first. Can you take another look at that?

**Comment by juliangruber** [comment]
@zeke sure, I think it would be the quickest if you added me to that heroku account

**Comment by zeke** [comment]
@juliangruber what's your Heroku email address?

**Comment by juliangruber** [comment]
:) it's mail@juliangruber.com

**Comment by zeke** [comment]
```
$ heroku access:add mail@juliangruber.com
Adding mail@juliangruber.com access to the app package-land... done
```

Note that the app name is still `package-land` ☝️

**Comment by juliangruber** [comment]
`CNAME` or `ALIAS` on root domains aren't supported by my registrar (iwantmyname), we could 

- move the domain
- use another ssl strategy
- not use ssl

What do you think?

**Comment by zeke** [comment]
move the domain? happy to pay for that.

**Comment by juliangruber** [comment]
i sent you a transfer code :)

**Comment by zeke** [comment]
<img width="926" alt="screen shot 2017-11-29 at 9 43 24 am" src="https://user-images.githubusercontent.com/2289/33390096-c70a52a2-d4e9-11e7-8d32-113f044327a4.png">

**Comment by juliangruber** [comment]
woot 🎆

**Comment by zeke** [comment]
All this stuff happened. It's live!

https://twitter.com/ghub_io

**Comment by juliangruber** [comment]
👏 ❤️
