### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by fregante** [nice-registry/ghub.io#892]
See:

- http://ghub.io/memoize
- http://ghub.io/satori

Should open repos from Sondra Sorhus and Vercel respectively, but point to their original repos. 

Also a package I published last week does not open GitHub at all:

- http://ghub.io/proper-event

**Comment by fregante** [comment]
This seems to be because the underlying package hasn’t been updated in 3 years: 

- https://github.com/nice-registry/ghub.io/pull/872

@zeke can you restart dependabot? They stop sending PRs if the repo is inactive I think

**Comment by zeke** [comment]
Yep it was stalled:

![Screenshot 2024-08-08 at 10 25 29](https://github.com/user-attachments/assets/a8fbe849-3c53-4a2b-b543-2e8c16f67b55)

I merged one of Dependabot's PRs to wake it back up.

I also went ahead and manually updated all-the-package-repos: https://github.com/nice-registry/ghub.io/commit/8ab8d54462a8f049058f34cf5a6a127b531e94b6

Ummm.. now I have to remember how and where this app is deployed. 🙈

**Comment by fregante** [comment]
You might also want to enable auto-merge on that specific dependency, so it doesn't fall out of date again:

- https://stackoverflow.com/questions/64116781/how-do-i-automerge-dependabot-updates-config-version-2

**Comment by zeke** [comment]
Okay got it deployed. For future reference. the app is still running on Heroku. It's called https://package-land.herokuapp.com/
