### ISSUE TITLE
async-to-genify is wrong

### ISSUE THREAD

**Issue by dy** [nice-registry/ghub.io#92]
https://ghub.io/async-to-genify Redirects to https://www.npmjs.com/package/async-to-genify, whereas there is a repo https://github.com/goto-bus-stop/async-to-genify

**Comment by zeke** [comment]
Thanks for letting me know. The https://github.com/nice-registry/all-the-package-repos updater stopped working, probably because of npm Inc invalidating all their tokens after a breach. I will get that updated and keep you posted.

**Comment by zeke** [comment]
It turns out that the out-of-date `all-the-package-repos` module is not the cause of this particular issue. The `async-to-genify` package doesn't have a `repository` field in its package.json: https://unpkg.com/async-to-genify@1.0.0/package.json
